### ISSUE TITLE
Aggiunta di una cartella con il push

### ISSUE THREAD

**Issue by dami013** [dami013/footballteam#3]
controlla bene @alessandroCassani

**Comment by dami013** [comment]
![image](https://user-images.githubusercontent.com/84079975/165555784-2003f8bc-271a-48cd-a9b4-4c2ef9408a5f.png)

**Comment by alessandroCassani** [comment]
si mea culpa

**Comment by dami013** [comment]
@alessandroCassani controllami perfavore che la modifica vada bene

**Comment by dami013** [comment]
operazione confermata
